# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\"#\n\x11SquareRootRequest\x12\x0e\n\x06number\x18\x01 \x01(\x02\"$\n\x12SquareRootResponse\x12\x0e\n\x06result\x18\x01 \x01(\x02\x32\x43\n\nCalculator\x12\x35\n\nSquareRoot\x12\x12.SquareRootRequest\x1a\x13.SquareRootResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SQUAREROOTREQUEST']._serialized_start=20
  _globals['_SQUAREROOTREQUEST']._serialized_end=55
  _globals['_SQUAREROOTRESPONSE']._serialized_start=57
  _globals['_SQUAREROOTRESPONSE']._serialized_end=93
  _globals['_CALCULATOR']._serialized_start=95
  _globals['_CALCULATOR']._serialized_end=162
# @@protoc_insertion_point(module_scope)
