version: '3'

services:
  grpc-client:
    build:
      context: .
      dockerfile: Dockerfile.client
    stdin_open: true  # Keep stdin open to allow user input
    tty: true  # Allocate a pseudo-TTY to allow user interaction

  grpc-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "50051:50051"
    depends_on:
      - grpc-client

